### ISSUE TITLE
Plugin doesn't work with Xcode 7.3

### ISSUE THREAD

**Issue by ghost** [mshibanami/DefaultMarginDisabler#2]
**Constrain to margins** is selected after installing plugin via Alcatraz and Xcode restart.

**Comment by mshibanami** [comment]
@a8b
I'M SO SORRY for forgetting about it! 😰
I added support for Xcode 7.3 just now. Please try again...

**Comment by Apofeozzz** [comment]
Xcode quit unexpectedly while using the DefaultMarginDisabler plug-in.

**Comment by Apofeozzz** [comment]
I can't run Xcode 7.3.1 because of this.
