### ISSUE TITLE
It'll be nice to remove margin here too

### ISSUE THREAD

**Issue by ghost** [mshibanami/DefaultMarginDisabler#3]
![monosnap 2016-03-29 11-53-02](https://cloud.githubusercontent.com/assets/6641859/14102731/0d5d90b4-f5a5-11e5-9434-0e3c98b2ef65.png)

**Comment by mshibanami** [comment]
@a8b
I agree!

But... I have no idea how to implement it. I'm a newbie about Xcode plugin development 😂
And my motivation is low because I almost never use it for some reasons.

Possibly I might try it someday. Sorry...

Of course I welcome any pull requests 👍

**Comment by mshibanami** [comment]
This repo is no longer supported. See more details here:
https://github.com/mshibanami/DefaultMarginDisabler/issues/6#issuecomment-284203844
